{
 "title": "Netology HW_10-03",
 "time": { "from": "2024-05-22T12:25:30.569Z", "to": "2024-05-22T13:44:32.697Z" },
 "panels": [
  {
   "title": "CPU Utilization, %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg (irate(node_cpu_seconds_total{mode=\"idle\"}[5m]) * 100))",
     "legendFormat": "CPU Utilization"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"nodeexporter\"}",
     "legendFormat": "Free Memory"
    }
   ]
  },
  {
   "title": "CPU  LA",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}",
     "legendFormat": "LA 1"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}",
     "legendFormat": "LA 5"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}",
     "legendFormat": "LA 15"
    }
   ]
  },
  {
   "title": "Free disk space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/mapper/centos-root\", fstype=\"xfs\", instance=\"nodeexporter:9100\", job=\"nodeexporter\", mountpoint=\"/\"}",
     "legendFormat": "Free disk space"
    }
   ]
  }
 ]
}